site_name: Pardot API Documentation

site_url: http://developer.pardot.com
site_description: Official documentation for the Pardot API
site_favicon: favicon.ico

repo_url: https://github.com/Pardot/api-docs

pages:

- ['index.md', 'Overview']

- ['index.md', 'API', 'Using the API']
- ['kb/api-version-3/object-field-references.md', 'API', 'Object Field References']
- ['kb/api-version-3/error-codes-messages.md', 'API', 'Error Codes & Messages']

- ['kb/api-version-3/custom-redirects.md', 'Methods', 'Custom Redirects']

- ['kb/api-version-3/dynamic-content.md', 'Methods', 'Dynamic Content']

- ['kb/api-version-3/emails.md', 'Methods', 'Email']

- ['kb/api-version-3/forms.md', 'Methods', 'Forms']

- ['kb/api-version-3/lists.md', 'Methods', 'Lists']

- ['kb/api-version-3/list-memberships.md', 'Methods', 'List Memberships']

- ['kb/api-version-3/opportunities.md', 'Methods', 'Opportunities']

- ['kb/api-version-3/prospects.md', 'Methods', 'Prospects']

- ['kb/api-version-3/prospect-accounts.md', 'Methods', 'Prospect Accounts']

- ['kb/api-version-3/visitor-activities.md', 'Methods', 'Tag Objects']

- ['kb/api-version-3/users.md', 'Methods', 'Users']

- ['kb/api-version-3/visitors.md', 'Methods', 'Visitors']

- ['kb/api-version-3/visitor-activities.md', 'Methods', 'Visitor Activities']

- ['kb/api-version-3/visits.md', 'Methods', 'Visits']

theme_dir: 'pardot_theme'